### PR TITLE
Plugin Test Extension 

### PR DESCRIPTION
**Pull request by Badya**
Related to: Create separated configs for test #45

Plugin uses only testVariants - good in case u definetly don't want to transform app's main code =)

### CODE REVIEW

**Comment by Archinamon** [comment]
@Badya There's too much changes. Why?)

**Comment by Badya** [comment]
@Archinamon  Maybe cause i renamed `AspectJWrapper -> AspectJPlugin` - as Martin Fowler said: "If you struggle with mistaking the name of some entity while searching for it - rename it" =)

**Comment by Badya** [comment]
I think build failing because of some travis conf issue using kotlin 1.1.2

**Comment by Badya** [comment]
@Archinamon after some tests i can say - it is broken

**Pull request closed without merging**
